#ifndef FINALLIBRARY_GLOBAL_H
#define FINALLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FINALLIBRARY_LIBRARY)
#  define FINALLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FINALLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FINALLIBRARY_GLOBAL_H
